export {default as DefaultLayout} from'./DefaultLayout'
export {default as DetailLayout} from'./Details'
export {default as LoginLayout} from './LoginLayout'
export {default as ProfileLayout} from './ProfileLayout'
export {default as CartLayout} from './CartLayout'
export {default as AdminLayout} from './AdminLayout'